# Generated by Django 3.1.4 on 2021-02-10 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('client_message', models.TextField(blank=True)),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone1', models.CharField(blank=True, max_length=15)),
                ('whatsapp_link', models.CharField(blank=True, max_length=400)),
                ('email', models.CharField(blank=True, max_length=300)),
                ('email_link', models.CharField(blank=True, max_length=400)),
                ('footer_details', models.TextField(blank=True)),
                ('twitter', models.CharField(blank=True, max_length=500)),
                ('facebook_link', models.CharField(blank=True, max_length=500)),
                ('insta_link', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
