# Generated by Django 3.1.4 on 2021-02-10 16:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('categorie', models.CharField(max_length=200)),
                ('project_main_photo', models.ImageField(upload_to='port/%Y/%m/%d/')),
                ('details_main', models.TextField(blank=True)),
                ('detail_2', models.TextField(blank=True)),
                ('product_design', models.TextField(blank=True)),
                ('product_design_photo', models.ImageField(blank=True, upload_to='port/%Y/%m/%d/')),
                ('design_photo2', models.ImageField(blank=True, upload_to='port/%Y/%m/%d/')),
                ('design_photo3', models.ImageField(blank=True, upload_to='port/%Y/%m/%d/')),
                ('design_photo4', models.ImageField(blank=True, upload_to='port/%Y/%m/%d/')),
                ('design_photo5', models.ImageField(blank=True, upload_to='port/%Y/%m/%d/')),
                ('design_detail_1', models.TextField(blank=True)),
                ('design_detail_2', models.TextField(blank=True)),
                ('final_photo_1', models.ImageField(blank=True, upload_to='port/%Y/%m/%d/')),
                ('final_photo_2', models.ImageField(blank=True, upload_to='port/%Y/%m/%d/')),
                ('final_photo_3', models.ImageField(blank=True, upload_to='port/%Y/%m/%d/')),
                ('final_photo_4', models.ImageField(blank=True, upload_to='port/%Y/%m/%d/')),
                ('final_photo_5', models.ImageField(blank=True, upload_to='port/%Y/%m/%d/')),
                ('final_photo_6', models.ImageField(blank=True, upload_to='port/%Y/%m/%d/')),
                ('final_photo_7', models.ImageField(blank=True, upload_to='port/%Y/%m/%d/')),
                ('final_photo_8', models.ImageField(blank=True, upload_to='port/%Y/%m/%d/')),
                ('final_photo_9', models.ImageField(blank=True, upload_to='port/%Y/%m/%d/')),
                ('final_photo_10', models.ImageField(blank=True, upload_to='port/%Y/%m/%d/')),
                ('design_detail_3', models.TextField(blank=True)),
                ('design_detail_4', models.TextField(blank=True)),
                ('show', models.BooleanField(default=True)),
                ('project_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('categorie', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('project_photo', models.ImageField(blank=True, upload_to='port/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('categorie', models.CharField(max_length=200)),
                ('project_main_photo', models.ImageField(upload_to='port/%Y/%m/%d/')),
                ('details_main', models.TextField(blank=True)),
                ('show', models.BooleanField(default=True)),
                ('project_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProjImag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='port/%Y/%m/%d/')),
                ('des', models.TextField(default=None, max_length=500)),
                ('Project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio.project')),
            ],
        ),
    ]
